### ISSUE TITLE
Create a detailed view

### ISSUE THREAD

**Issue by MrValdez** [drcarino/capstoneproposal#1]
You've written a quick overview of your capstone.

Make a new file that will contain the details on your overview. For example:

1. Timeline. How are you going to budget your time in the development of the system?
1. Number of people. How can you justify these resources? What is your basis for having 2 of each?

**Comment by drcarino** [comment]
Answered this issue on a new file
https://github.com/drcarino/capstoneproposal/blob/master/details.txt
